[project]
name = "mayflower-task"
version = "0.1.0"
description = ""
authors = [
    {name = "Lilly",email = "lg1527058@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "fastapi (>=0.115.12,<0.116.0)",
    "uvicorn (>=0.34.2,<0.35.0)",
    "python-dotenv (>=1.1.0,<2.0.0)",
    "psycopg2-binary (>=2.9.10,<3.0.0)",
    "langgraph (>=0.3.31,<0.4.0)",
    "langchain (>=0.3.23,<0.4.0)",
    "langchain-ollama (>=0.3.2,<0.4.0)",
    "sqlmodel (>=0.0.24,<0.0.25)",
    "langchain-community (>=0.3.21,<0.4.0)",
    "rhymetagger (>=0.2.9,<0.3.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
alembic = "^1.15.2"
